Use ulong_ instead of size_type for dynamic_bitset::count()
This fixes the following compilation error on Mac OS X:

"error: implicit instantiation of undefined template
'boost::compute::detail::type_name_trait<unsigned long>'"